name: Terraform Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. List the contents of the terraform directory (for debugging)
      - name: List files in terraform directory
        run: ls -R terraform
        # This will display all files in the terraform folder

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="key_name=${{ secrets.EC2_KEY_NAME }}"
        working-directory: terraform

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="key_name=${{ secrets.EC2_KEY_NAME }}"
        working-directory: terraform
